apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: tsm-event-source-test
  namespace: tsm
  labels:
    team: tsm
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 90
  port: 3000
  kafka:
    pool: nav-prod
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 2500m
      memory: 1Gi
    requests:
      cpu: 150m
      memory: 600Mi
  env:
    - name: TOPIC_SEEK_OFFSET
      value: |
        {
          "teamsykmelding.syfo-bekreftet-sykmelding": [
            [0, "182653"],
            [1, "175834"],
            [2, "346481"]
          ],
          "teamsykmelding.syfo-sendt-sykmelding": [
            [0, "6319965"],
            [1, "6261807"],
            [2, "6304650"]
          ]
        }
